/**
 * @typedef {{
 *  postMessage: (message: *, transfer?: Transferable[]) => void
 * }} Client
 */


// Auto-generated by .githooks/pre-commit (a content hash of every file this cache actually covers
// - index.html, css/**, js/**, static/**) - don't hand-edit this, it's overwritten on the next
// commit that touches any of those. See "Service worker caching" in CLAUDE.md for the one-time
// `npm install` setup that wires the hook up (frontend/package.json's "prepare" script). Ported
// from the sibling sonar project's own cacheServiceWorker.js/.githooks/pre-commit pair.
const cacheVersion = 'v75cbdafa46a7';
const appCache = cacheVersion + '__' + 'app-cache';
const cacheWhitelist = [appCache];

// Dev-only escape hatch: flip to true and reload to bypass the cache entirely (every request goes
// straight to the network, nothing is read from or written to caches) - the code equivalent of
// devtools' Application > Service Workers > "Bypass for network", but persistent across tabs/
// restarts without having to remember to flip a devtools checkbox every session. Never commit this
// as true - it defeats the whole point of cache-first serving for real users.
const BYPASS_CACHE = false;

self.addEventListener('fetch', e =>
  // @ts-ignore
  e.respondWith(returnCachedFileOrFetchIt(e))
);


/**
 * Send message to clients
 * @param {*} msg
 * @param {Transferable[]} [transfer]
 */
function sendToClients(msg, transfer) {
  // @ts-ignore
  self.clients.matchAll()
    .then(
      /** @param {Client[]} clients */
      clients => {
        if (!clients || !clients.length) { console.info(' ** no clients'); }
        clients.forEach(c => c.postMessage({ msg, transfer }));
      })
    .catch(
      /** @param {Event} e */
      e => console.error(' ** @sendToClients', e)
    );
}

/** Install */
self.addEventListener('install', () => {
  console.info(' ** Install cache. Version:', cacheVersion);
  // @ts-ignore
  self.skipWaiting();
});

/** Activate */
self.addEventListener('activate', e => {
  console.info(' ** Activate cache. Version:', cacheVersion);
  // Without this, a brand new install doesn't take control of the page that triggered it - only
  // the *next* navigation would be. Cache-first serving only populates the cache as a side effect
  // of requests actually going through this SW, so a first-time visitor who goes offline before
  // ever reloading would find nothing cached at all. claim() lets initializeCache.js detect
  // control immediately; see its own comment for what it does with that.
  // @ts-ignore
  e.waitUntil(self.clients.claim());
  sendToClients({
    status: 'ACTIVATING',
    cacheWhitelist,
    cacheVersion,
  });
});

/**
 * Push notification - reaches this listener regardless of cache state or BYPASS_CACHE above; a
 * push can arrive at any time, unrelated to the fetch-caching strategy.
 */
self.addEventListener('push', e => {
  // @ts-ignore
  const payload = e.data ? e.data.json() : {};
  const { title = 'FridgeTrack', body = '', url = '/' } = payload;
  // @ts-ignore
  e.waitUntil(self.registration.showNotification(title, {
    body,
    icon: '/static/icons/android-chrome-192x192.png',
    badge: '/static/icons/android-chrome-192x192.png',
    data: { url },
  }));
});

/** Opens (or focuses) the app to the notification's target url on click */
self.addEventListener('notificationclick', e => {
  // @ts-ignore
  const url = e.notification.data?.url || '/';
  // @ts-ignore
  e.notification.close();
  // @ts-ignore
  e.waitUntil(self.clients.openWindow(url));
});


/**
 * @param {Event} event
 */
async function returnCachedFileOrFetchIt(event) {
  try {
    // @ts-ignore
    /** @type {Request} */
    const request = event.request;
    const url = new URL(request.url);

    if (url.protocol === 'chrome-extension:') {
      return fetch(request);
    }

    // The Cache API's put() throws on anything but GET, and API calls must never be served
    // stale/cached anyway - apiCaller.js's apiCall() always POSTs to /api/*, so this excludes
    // every real API request by either check; both are kept as defense-in-depth in case that
    // ever changes.
    if (request.method !== 'GET' || url.pathname.startsWith('/api/')) {
      return fetch(request);
    }

    if (BYPASS_CACHE) {
      return fetch(request);
    }

    // Client-side routes (e.g. /item/42) all serve the same index.html shell - mirrors
    // requestHandler.js's own SPA-fallback heuristic (last path segment has no dot) so every one
    // of them cache-hits/populates a single canonical entry instead of each route becoming its
    // own separate (duplicate, and individually stale-able) cache entry.
    const lastSegment = url.pathname.split('/').pop() || '';
    const cacheKey = lastSegment.includes('.') ? request : new Request(new URL('/', url).href);

    return cacheFirst(request, cacheKey);
  } catch (e) {
    console.error('Error returning cached response', e);
  }
}

/**
 * @param {Request} request - what to actually fetch on a cache miss
 * @param {Request} cacheKey - what to key the cache lookup/write on (see the SPA note above -
 *   this can differ from `request` itself)
 */
async function cacheFirst(request, cacheKey) {
  // @ts-ignore
  const cachedResponse = await caches.match(cacheKey);
  if (cachedResponse) {
    return cachedResponse;
  }
  // @ts-ignore
  const fetchResponse = await fetch(request);
  const cache = await caches.open(appCache);
  // @ts-ignore
  cache.put(cacheKey, fetchResponse.clone());
  return fetchResponse;
}
